backend:
  name: github
  repo: IanCassTwo/astro.wheep.co.uk
  base_url: https://astro.wheep.co.uk
  automatic_deployments: false

media_folder: 'assets/images/_pristine'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Preview', name: 'preview', widget: 'image', 'allow_mutiple':'false' }
      - { label: 'Workflow', name: 'workflow', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  
  - name: 'equipment'
    label: 'Equipment'
    folder: 'equipment/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Equipment' }

  - name: 'tutorials'
    label: 'Tutorials'
    folder: 'tutorials/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Tutorials' }

  - name: 'software'
    label: 'Software'
    folder: 'software/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Software' }

  - name: 'glossary'
    label: 'Glossary'
    folder: 'glossary/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Parent', name: 'parent', widget: 'hidden', default: 'Glossary' }

  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'About'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Nav Order', name: 'nav_order', widget: 'number'}
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Resources'
        name: 'resources'
        file: 'resources.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Nav Order', name: 'nav_order', widget: 'number'}
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
